'use client'
import { Inter } from 'next/font/google'

import './globals.css'
import { cn } from '@/lib/utils'
// import SideNavbar from '@/components/SideNavbar'
import { Toaster } from 'react-hot-toast'
import { useUser } from '@/hooks/use-user'
import { redirect, usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  const user = useUser()
  const pathName = usePathname()

  const authRoutes = ['/', '/forgot-password']
  const isInAuthRoute = authRoutes.includes(pathName)

  if (user && isInAuthRoute) return redirect('/dashboard')
  return (
    <html lang='en'>
      <body
        className={cn('min-h-screen w-full bg-white  flex', inter.className, {
          'debug-screens': process.env.NODE_ENV === 'development'
        })}
      >
        {
          //? Sidebar
        }
        {/* <p className='border'>Sidebar</p> */}
        {/* <SideNavbar /> */}
        {
          //? MainPage
        }
        <div className='p-8 w-full'>
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  )
}
